import React, { useState, useEffect, useCallback } from 'react'
import Shell from '../components/Shell'
import Card from '../components/ui/Card'
import Badge from '../components/ui/Badge'
import KPICard from '../components/KPICard'
import DataTable, { Column } from '../components/DataTable'
import { formatCurrency, timeAgo } from '../lib/utils'

interface POLineItem {
  id: number
  productId: string
  productTitle: string
  qty: number
  costPerUnit: number
  totalCost: number
}

interface PurchaseOrder {
  id: number
  poNumber: string
  status: string
  totalQty: number
  totalCost: number
  notes: string
  createdBy: string
  createdAt: string
  updatedAt: string
  lineItems: POLineItem[]
}

interface InboundItem {
  productId: string
  productTitle: string
  inboundQty: number
  poNumbers: string[]
}

const statusVariant: Record<string, 'success' | 'warning' | 'error' | 'neutral'> = {
  draft: 'neutral',
  ordered: 'warning',
  shipped: 'success',
  received: 'success',
}

const statusFlow = ['draft', 'ordered', 'shipped', 'received']

const poColumns: Column[] = [
  { key: 'poNumber', label: 'PO #', tooltip: 'Auto-generated by Hank when products need restocking' },
  {
    key: 'status',
    label: 'Status',
    tooltip: 'Draft → Ordered → Shipped → Received',
    render: (v: string) => <Badge variant={statusVariant[v] || 'neutral'}>{v}</Badge>,
  },
  { key: 'totalQty', label: 'Units', tooltip: 'Total units in this purchase order' },
  {
    key: 'totalCost',
    label: 'Est. Cost',
    tooltip: 'Estimated cost at 40% of retail price',
    render: (v: number) => formatCurrency(v),
  },
  { key: 'createdBy', label: 'Created By' },
  {
    key: 'createdAt',
    label: 'Created',
    render: (v: string) => v ? timeAgo(v) : '—',
  },
]

const lineItemColumns: Column[] = [
  { key: 'productTitle', label: 'Product' },
  { key: 'qty', label: 'Qty' },
  {
    key: 'costPerUnit',
    label: 'Unit Cost',
    render: (v: number) => formatCurrency(v),
  },
  {
    key: 'totalCost',
    label: 'Total',
    render: (v: number) => formatCurrency(v),
  },
]

const inboundColumns: Column[] = [
  { key: 'productTitle', label: 'Product' },
  { key: 'inboundQty', label: 'Inbound Units', tooltip: 'Units on the way from active POs — factored into Hank\'s reorder calculations' },
  {
    key: 'poNumbers',
    label: 'From POs',
    render: (v: string[]) => v?.join(', ') || '—',
  },
]

export default function PurchaseOrdersPage() {
  const [pos, setPOs] = useState<PurchaseOrder[]>([])
  const [inbound, setInbound] = useState<InboundItem[]>([])
  const [selectedPO, setSelectedPO] = useState<PurchaseOrder | null>(null)

  const fetchData = useCallback(async () => {
    try {
      const [posRes, inboundRes] = await Promise.all([
        fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/purchase-orders`),
        fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/purchase-orders/inbound`),
      ])
      if (posRes.ok) setPOs(await posRes.json())
      if (inboundRes.ok) setInbound(await inboundRes.json())
    } catch {}
  }, [])

  useEffect(() => {
    fetchData()
    const interval = setInterval(fetchData, 10000)
    return () => clearInterval(interval)
  }, [fetchData])

  const advanceStatus = async (po: PurchaseOrder) => {
    const currentIdx = statusFlow.indexOf(po.status)
    if (currentIdx >= statusFlow.length - 1) return
    const nextStatus = statusFlow[currentIdx + 1]

    try {
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/purchase-orders/${po.id}`,
        {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ status: nextStatus }),
        }
      )
      if (res.ok) fetchData()
    } catch {}
  }

  const totalInbound = inbound.reduce((sum, i) => sum + i.inboundQty, 0)
  const totalPOCost = pos.reduce((sum, p) => sum + p.totalCost, 0)
  const draftCount = pos.filter((p) => p.status === 'draft').length
  const inTransit = pos.filter((p) => p.status === 'ordered' || p.status === 'shipped').length

  return (
    <Shell title="Purchase Orders">
      <div className="space-y-4">
        {/* KPIs */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
          <KPICard title="Active POs" value={pos.length} tooltip="Purchase orders created by Hank (Supply Chain agent)" />
          <KPICard title="Drafts" value={draftCount} tooltip="POs awaiting approval — review and advance to 'ordered'" />
          <KPICard title="In Transit" value={inTransit} tooltip="POs that have been ordered or shipped" />
          <KPICard title="Total Inbound" value={totalInbound} suffix="units" tooltip="Total units on the way — Hank factors these into reorder calculations" />
        </div>

        {/* PO Table */}
        <Card title="Purchase Orders" subtitle={`${pos.length} orders — ${formatCurrency(totalPOCost)} total estimated cost`}>
          {pos.length === 0 ? (
            <p className="text-xs text-text-tertiary py-8 text-center">
              No purchase orders yet — Hank will create them when products need restocking
            </p>
          ) : (
            <DataTable
              columns={poColumns}
              data={pos}
              onRowClick={(row) => setSelectedPO(selectedPO?.id === row.id ? null : row)}
            />
          )}
        </Card>

        {/* Selected PO Detail */}
        {selectedPO && (
          <Card
            title={`${selectedPO.poNumber} — Line Items`}
            subtitle={selectedPO.notes}
            action={
              selectedPO.status !== 'received' ? (
                <button
                  onClick={() => advanceStatus(selectedPO)}
                  className="text-xs bg-accent/10 text-accent px-3 py-1.5 rounded-md hover:bg-accent/20 transition-colors"
                >
                  Advance to {statusFlow[statusFlow.indexOf(selectedPO.status) + 1]}
                </button>
              ) : undefined
            }
          >
            <DataTable columns={lineItemColumns} data={selectedPO.lineItems} />
          </Card>
        )}

        {/* Inbound Stock */}
        {inbound.length > 0 && (
          <Card title="Inbound Stock" subtitle="Units on the way — factored into Hank's reorder calculations">
            <DataTable columns={inboundColumns} data={inbound} />
          </Card>
        )}
      </div>
    </Shell>
  )
}
